#!/bin/bash 

#Powderday cluster setup convenience script for SLURM queue manager
#on HiPerGator at the University of FLorida.  This sets up the model
#files for a cosmological simulation where we want to model many
#galaxies at once.

#Notes of interest:

#1. This does *not* set up the parameters_master.py file: it is
#assumed that you will *very carefully* set this up yourself.

#2. This requires bash versions >= 3.0.  To check, type at the shell
#prompt: 

#> echo $BASH_VERSION

n_nodes=$1
model_dir=$2
hydro_dir=$3
out_dir=$4
model_run_name=$5
COSMOFLAG=$6
FILTERFLAG=$7
model_dir_remote=$8
hydro_dir_remote=$9
xpos=${10}
ypos=${11}
zpos=${12}
galaxy=${13}
snap=${14}
tcmb=${15}
gal_count=${16}
sim_id=${17}

echo "processing model file for galaxy,snapshot:  $galaxy,$snap"


#clear the pyc files
rm -f *.pyc

#set up the model_**.py file
echo "setting up the output directory in case it doesnt already exist"
echo "snap is: $snap"
echo "model dir is: $model_dir"
mkdir $model_dir


echo "setting up the PD run output directory in case it doesnt already exist"
echo "snap is: $snap"
echo "output dir is: $out_dir"
mkdir $out_dir
logs="${out_dir}outlogs"
mkdir $logs


filem="${model_dir}snap${snap}_galaxy${galaxy}.py"
echo "writing to $filem"
rm -f $filem


echo "#Snapshot Parameters" >> $filem
echo "#<Parameter File Auto-Generated by setup_all_cluster.sh>" >> $filem
echo "snapshot_num =  $snap" >> $filem
echo "galaxy_num = $galaxy" >>$filem
echo -e "\n" >> $filem

echo -e "galaxy_num_str = str(galaxy_num)" >> $filem

echo -e "\n" >>$filem
echo -e "snapnum_str = str(snapshot_num)" >> $filem

echo -e "\n" >>$filem

if [ $COSMOFLAG -eq 1 ]
then
    echo "hydro_dir = '$hydro_dir_remote/snapdir_'+snapnum_str+'/'">>$filem
    echo "snapshot_name = 'snapshot_'+snapnum_str+'.0.hdf5'" >>$filem
elif [ $FILTERFLAG -eq 1 ]
then
    echo "hydro_dir = '$hydro_dir_remote'">>$filem
    echo "snapshot_name = 'galaxy_'+str(galaxy_num)+'.hdf5'">>$filem

else
    echo "hydro_dir = '$hydro_dir_remote/'">>$filem
    echo "snapshot_name = 'snapshot_'+snapnum_str+'.hdf5'" >>$filem
fi


echo -e "\n" >>$filem

echo "#where the files should go" >>$filem
echo "PD_output_dir = '${out_dir}' ">>$filem
echo "Auto_TF_file = 'snap'+snapnum_str+'.logical' ">>$filem
echo "Auto_dustdens_file = 'snap'+snapnum_str+'.dustdens' ">>$filem

echo -e "\n\n" >>$filem
echo "#===============================================" >>$filem
echo "#FILE I/O" >>$filem
echo "#===============================================" >>$filem
echo "inputfile = PD_output_dir+'snap'+snapnum_str+'.galaxy'+galaxy_num_str+'.rtin'" >>$filem
echo "outputfile = PD_output_dir+'snap'+snapnum_str+'.galaxy'+galaxy_num_str+'.rtout'" >>$filem

echo -e "\n\n" >>$filem
echo "#===============================================" >>$filem
echo "#GRID POSITIONS" >>$filem
echo "#===============================================" >>$filem
echo "x_cent = ${xpos}" >>$filem
echo "y_cent = ${ypos}" >>$filem
echo "z_cent = ${zpos}" >>$filem

echo -e "\n\n" >>$filem
echo "#===============================================" >>$filem
echo "#CMB INFORMATION" >>$filem
echo "#===============================================" >>$filem
echo "TCMB = ${tcmb}" >>$filem

echo "writing slurm submission master script file"
qsubfile="${model_dir}master.snap${snap}.job"
rm -f $qsubfile
echo $qsubfile

echo "#! /bin/bash" >>$qsubfile
echo "#SBATCH --job-name=${model_run_name}.snap${snap}" >>$qsubfile
echo "#SBATCH --output=pd.master.snap${snap}.o" >>$qsubfile
echo "#SBATCH --error=pd.master.snap${snap}.e" >>$qsubfile
echo "#SBATCH --mail-type=ALL" >>$qsubfile
echo "#SBATCH --mail-user=d.zimmerman@ufl.edu" >>$qsubfile
echo "#SBATCH --time=72:00:00" >>$qsubfile
echo "#SBATCH --tasks-per-node=32">>$qsubfile
echo "#SBATCH --nodes=$n_nodes">>$qsubfile
echo "#SBATCH --mem-per-cpu=3800">>$qsubfile
echo "#SBATCH --account=narayanan">>$qsubfile
echo "#SBATCH --qos=narayanan-b">>$qsubfile
echo "#SBATCH --array=0-${gal_count}%10">>$qsubfile
echo -e "\n">>$qsubfile
echo -e "\n" >>$qsubfile

echo "cd /home/d.zimmerman">>$qsubfile
echo "module purge">>$qsubfile
echo "source .bashrc">>$qsubfile
echo "conda activate /blue/narayanan/d.zimmerman/code_environments/master_el8_environment">>$qsubfile
echo -e "\n">>$qsubfile
echo "module load git">>$qsubfile
echo "module load intel/2020.0.166">>$qsubfile
echo "module load openmpi/4.1.5">>$qsubfile
echo "module load hdf5/1.14.1">>$qsubfile
echo -e "\n">>$qsubfile

echo "ID=\$(awk '{if(NR==(n+1)) print int(\$0)}' n=\${SLURM_ARRAY_TASK_ID} /orange/narayanan/d.zimmerman/camels_results/filtered/${model_run_name}/snap${snap}/snap${snap}_gas_gals.txt)">>$qsubfile
echo -e "\n">>$qsubfile

echo "cd /home/d.zimmerman/powderday/">>$qsubfile
echo "pd_front_end.py $model_dir_remote parameters_master_camels snap${snap}_galaxy\${ID} > ${out_dir}outlogs/snap${snap}_galaxy\${ID}.log">>$qsubfile
echo "date"
#done

